version: '3'

services:
  worker_app:
    image: 384951611022.dkr.ecr.us-east-1.amazonaws.com/spreeproject/server_app:production
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 2a87061a0d90bda24992b0d0d9f8925a
