version: '3'

services:
  web_server:
    image: 384951611022.dkr.ecr.us-east-1.amazonaws.com/spreeproject/web_server:production
    ports:
      - 8080:8080
    links:
      - server_app

  server_app:
    image: 384951611022.dkr.ecr.us-east-1.amazonaws.com/spreeproject/server_app:production
    command: bundle exec puma -C config/puma.rb
    entrypoint: "./docker-entrypoint.sh"
    expose:
      - 3000
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 2a87061a0d90bda24992b0d0d9f8925a
